using VulpesTool;
public enum TypeItem : ushort
{
    None,
    [EnumCategory("Еда")]
    Apple,
    [EnumCategory("Предмет")]
    Basket,
    Barrel,
    Table_Cardboard,
    Chair_Cardboard,
    TNT,
    TNT_3,
    TNT_3_Timer,
    Barrel_Detonator,
    Barrel_Detonator_Timer,
    TazWanted,
    DoorLegasy,
    Bench,
    TrashCanMini,
    [EnumCategory("Еда")]
    CocaCola,
    [EnumCategory("Предмет")]
    Box,
    BoxMetal,
    PadlockRed,
    PadlockGreen,
    PadlockBlue,
    PadlockYellow,
    PadlockBlack,
    PadlockWhite,
    KeyRed,
    KeyGreen,
    KeyBlue,
    KeyYellow,
    KeyBlack,
    KeyWhite,
    Wardrobe,
    Bed,
    [EnumCategory("Еда")]
    Banana,
    Melon,
    Pineapple,
    [EnumCategory("Оружие")]
    Scrap,
    Sword,
    [EnumCategory("Предмет")]
    Barrel_Content,
    [EnumCategory("Здания")]
    Tower_Crane
}
